name: Scheduler

# Ensure at-most one scheduler instance is running at any given time.
concurrency: iris-scheduler

on:
  push:
    paths-ignore: ['README.md']
  schedule:
    - cron:  '0/15 * * * *'

jobs:
  main:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: dioptra-io/setup-poetry-action@v1
      - name: Decompress prefixes lists
        run: zstd -df prefixes/*.zst
      - name: Install the scheduler
        run: poetry install
      - name: Run the scheduler
        run: poetry run iris-scheduler
        env:
          IRIS_BASE_URL: ${{ secrets.IRIS_BASE_URL }}
          IRIS_USERNAME: ${{ secrets.IRIS_USERNAME }}
          IRIS_PASSWORD: ${{ secrets.IRIS_PASSWORD }}
          PYCH_BASE_URL: ${{ secrets.PYCH_BASE_URL }}
          PYCH_DATABASE: ${{ secrets.PYCH_DATABASE }}
          PYCH_USERNAME: ${{ secrets.PYCH_USERNAME }}
          PYCH_PASSWORD: ${{ secrets.PYCH_PASSWORD }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: MEASUREMENTS.md
