name: Scheduler

on:
  push:
    paths-ignore: ['**.md']
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Cache
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: .venv/
          key: venv-202107-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run scheduler
        run: .venv/bin/python3 scheduler.py
        env:
          IRIS_USERNAME: ${{ secrets.IRIS_USERNAME }}
          IRIS_PASSWORD: ${{ secrets.IRIS_PASSWORD }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          file_pattern: MEASUREMENTS.md
