name: Scheduler

on:
  push:
  schedule:
    - cron:  '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Cache
        id: cache
        uses: actions/cache@v2.1.5
        with:
          path: .venv/
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run scheduler
        run: .venv/bin/python3 scheduler.py
        env:
          IRIS_USERNAME: ${{ secrets.IRIS_USERNAME }}
          IRIS_PASSWORD: ${{ secrets.IRIS_PASSWORD }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: MEASUREMENTS.md
